/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-08-19 03:07:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class show_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1597805476295L));
    _jspx_dependants.put("/form.jsp", Long.valueOf(1597805889206L));
    _jspx_dependants.put("/BSLoad.jsp", Long.valueOf(1597805476293L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1597805476296L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width\", initial-scale=\"1\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/form.css\">\r\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("\n");
      out.write("<!-- Bootstrap CSS -->\n");
      out.write("  <link href=\"vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/LINC_MAIN.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\" integrity=\"sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z\" crossorigin=\"anonymous\">\n");
      out.write("  <!-- <script src=\"https://code.jquery.com/jquery-3.2.1.min.js\" integrity=\"sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=\" crossorigin=\"anonymous\"></script> -->\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\n");
      out.write("\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrp.js\"></script>\r\n");
      out.write("\n");
      out.write("<header id=\"header\">\n");
      out.write("\n");
      out.write("      <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark fixed-top\" id=\"mainNav\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("          <a class=\"navbar-brand js-scroll-trigger\" href=\"#page-top\">Logo Here</a>\n");
      out.write("          <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("          </button>\n");
      out.write("\n");
      out.write("\n");
      out.write("          <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("            <ul class=\"navbar-nav mr-auto\">\n");
      out.write("              <li class=\"nav-item \">\n");
      out.write("                <a class=\"nav-link\" href=\"#\">게시판 <span class=\"sr-only\">(current)</span></a>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"nav-item\">\n");
      out.write("                <a class=\"nav-link\" href=\"#\">블로그</a>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"nav-item dropdown\">\n");
      out.write("                <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("                  Dropdown\n");
      out.write("                </a>\n");
      out.write("                <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("                  <a class=\"dropdown-item\" href=\"#\">Action</a>\n");
      out.write("                  <a class=\"dropdown-item\" href=\"#\">Another action</a>\n");
      out.write("                  <div class=\"dropdown-divider\"></div>\n");
      out.write("                  <a class=\"dropdown-item\" href=\"#\">Something else here</a>\n");
      out.write("                </div>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"nav-item\">\n");
      out.write("                <a class=\"nav-link disabled\" href=\"#\" tabindex=\"-1\" aria-disabled=\"true\">비활성화</a>\n");
      out.write("              </li>\n");
      out.write("            </ul>\n");
      out.write("            <form class=\"form-inline my-2 my-lg-0\">\n");
      out.write("              <input class=\"form-control mr-sm-2\" type=\"search\"  placeholder=\"Search\" aria-label=\"Search\">\n");
      out.write("              <button class=\"btn btn-outline-success my-2 my-sm-0 mx-2\" type=\"submit\">Search</button>\n");
      out.write("            </form>\n");
      out.write("            <button class=\"btn btn-outline-primary my-2 my-sm-0 mx-2\">로그인</button>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("      </nav>\n");
      out.write("\n");
      out.write("    </header>\n");
      out.write("    <div class=\"mb-5\">\n");
      out.write("    \n");
      out.write("    </div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class =\"container\" >\r\n");
      out.write("<div class = \"border-bottom\" style =\"margin-bottom:50px; margin-top:100px; font-weight: bold ; font-size:50px;\">음악 게시판\r\n");
      out.write("</div>\r\n");
      out.write("<p style = \"font-weight: bold ; font-size:20px;\">[음악]&nbsp;&nbsp;안녕하세요\r\n");
      out.write("<div style =\"border-bottom: 2px solid blue; margin-bottom:5\r\n");
      out.write("0px\">\r\n");
      out.write("<span>2020.08.11 00:20</span><span>&nbsp;&nbsp;|&nbsp;&nbsp;용용</span>\r\n");
      out.write("<span style =\"float:right\">&nbsp;&nbsp;|&nbsp;&nbsp;댓글&nbsp;&nbsp;2</span>\r\n");
      out.write("<span style =\"float:right\">&nbsp;&nbsp;|&nbsp;&nbsp;추천&nbsp;&nbsp;1</span>\r\n");
      out.write("<span style =\"float:right\">&nbsp;&nbsp;&nbsp;&nbsp;조회수&nbsp;&nbsp;20</span>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<textarea class=\"form-control\" placeholder=\"글내용\" maxlength=\"2048\" style=\"height:350px; margin-top:50px;margin-bottom:50px;\"></textarea>\r\n");
      out.write("<div style=\"text-align: center;\"><img src=\"heart.png\" style=\"height:100px;\"> <img src=\"heart2.png\" style=\"height:100px;\"><img src=\"attend.jpg\" style=\"height:100px;\"><div><p style=\"display:inline\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;호감&nbsp;:&nbsp;&nbsp;</p><p style=\"display:inline; color:red;\">5&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p><span>비호감&nbsp;:&nbsp;&nbsp;</span><span>0&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span>신고하기!</span></div></div>\r\n");
      out.write("<div class = \"border-bottom\" style=\"margin-bottom:50px\">댓글 3개</div>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("         <table style=\"text-align: center; border: 1px solid #dddddd;margin-top:100px\">\r\n");
      out.write("            <thead>\r\n");
      out.write("               <tr style =\"border-bottom: 2px solid blue; border-top: 1px solid blue; height:40px;\">\r\n");
      out.write("                  <th style=\"background-color: #eeeeee; text-align: center;\"width=\"100px;\">글번호</th>\r\n");
      out.write("                  <th style=\"background-color: #eeeeee; text-align: center;\"width=\"500px;\">제목</th>\r\n");
      out.write("                  <th style=\"background-color: #eeeeee; text-align: center;\"width=\"150px;\">글쓴이</th>\r\n");
      out.write("                  <th style=\"background-color: #eeeeee; text-align: center;\"width=\"60px;\">조회수</th>\r\n");
      out.write("                  <th style=\"background-color: #eeeeee; text-align: center;\"width=\"60px;\">추천수</th>\r\n");
      out.write("                  <th style=\"background-color: #eeeeee; text-align: center;\"width=\"60px;\">작성일</th>\r\n");
      out.write("               </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody id=\"serchtext4\">\r\n");
      out.write("               <tr style=\"height:20px; border: 1px solid #dddddd\">\r\n");
      out.write("                  <td>1</td>\r\n");
      out.write("                  <td >아아이</td>\r\n");
      out.write("                  <td>오늘은</td>\r\n");
      out.write("                  <td>1</td>\r\n");
      out.write("                  <td>1</td>\r\n");
      out.write("                  <td>08-01</td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr style=\"height:20px; border: 1px solid #dddddd\">\r\n");
      out.write("                  <td>1</td>\r\n");
      out.write("                  <td>아아이</td>\r\n");
      out.write("                  <td>오늘은</td>\r\n");
      out.write("                  <td>1</td>\r\n");
      out.write("                  <td>1</td>\r\n");
      out.write("                  <td>08-01</td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr style=\"height:20px; border: 1px solid #dddddd\">\r\n");
      out.write("                  <td>1</td>\r\n");
      out.write("                  <td>아아이</td>\r\n");
      out.write("                  <td>오늘은</td>\r\n");
      out.write("                  <td>1</td>\r\n");
      out.write("                  <td>1</td>\r\n");
      out.write("                  <td>08-01</td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr style=\"height:20px; border: 1px solid #dddddd\">\r\n");
      out.write("                  <td>1</td>\r\n");
      out.write("                  <td>아아이</td>\r\n");
      out.write("                  <td>오늘은</td>\r\n");
      out.write("                  <td>1</td>\r\n");
      out.write("                  <td>1</td>\r\n");
      out.write("                  <td>08-01</td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr style=\"height:20px; border: 1px solid #dddddd\">\r\n");
      out.write("                  <td>1</td>\r\n");
      out.write("                  <td>아아이</td>\r\n");
      out.write("                  <td>오늘은</td>\r\n");
      out.write("                  <td>1</td>\r\n");
      out.write("                  <td>1</td>\r\n");
      out.write("                  <td>08-01</td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr style=\"height:20px; border: 1px solid #dddddd\">\r\n");
      out.write("                  <td>1</td>\r\n");
      out.write("                  <td>아아이</td>\r\n");
      out.write("                  <td>오늘은</td>\r\n");
      out.write("                  <td>1</td>\r\n");
      out.write("                  <td>1</td>\r\n");
      out.write("                  <td>08-01</td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr style=\"height:20px; border: 1px solid #dddddd\">\r\n");
      out.write("                  <td>1</td>\r\n");
      out.write("                  <td>아아이</td>\r\n");
      out.write("                  <td>오늘은</td>\r\n");
      out.write("                  <td>1</td>\r\n");
      out.write("                  <td>1</td>\r\n");
      out.write("                  <td>08-01</td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr style=\"height:20px; border: 1px solid #dddddd\">\r\n");
      out.write("                  <td>1</td>\r\n");
      out.write("                  <td>아아이</td>\r\n");
      out.write("                  <td>오늘은</td>\r\n");
      out.write("                  <td>1</td>\r\n");
      out.write("                  <td>1</td>\r\n");
      out.write("                  <td>08-01</td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr style=\"height:20px; border-bottom: 2px solid blue;\">\r\n");
      out.write("                  <td>1</td>\r\n");
      out.write("                  <td>아아이</td>\r\n");
      out.write("                  <td>오늘은</td>\r\n");
      out.write("                  <td>1</td>\r\n");
      out.write("                  <td>1</td>\r\n");
      out.write("                  <td>08-01</td>\r\n");
      out.write("               </tr>\r\n");
      out.write("            </tbody>\r\n");
      out.write("         </table>\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         </div>\r\n");
      out.write("         \r\n");
      out.write("         </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div style=\"margin-top:100px\">\r\n");
      out.write("\r\n");
      out.write("  ");
      out.write("<footer class=\"py-5 bg-dark\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <p class=\"m-0 text-center text-white\">Copyright &copy; 2020</p>\n");
      out.write("      </div>\n");
      out.write(" </footer>");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
